name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.5
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - matplotlib
  - bokeh
  - seaborn
  - missingno
  - itertools
  - xgboost
